tracebility/urls.py
from django.conf import settings

from django.contrib import admin
from django.conf.urls.static import static
from django.views.static import serve

from django.urls import path, include, re_path
from pgsoc.views import lgtracer, potracer
from pgsoc.views import onboard_fc, dashboard, onboard_lg
from pgsoc.views import view_lg, add_lg_farmer, add_lg_product, product_lg_details, add_lg_product_to_certification
from pgsoc.views import add_po_product, product_po_details, view_po, add_po_product_to_certification, onboard_po

from user.views import login_view, logout_view 

urlpatterns = [
    path('admin/', admin.site.urls),
    
    re_path('login/',login_view,name="login"),
    re_path('logout/',logout_view,name="logout"),
    
    path('',dashboard,name="dashboard"),
    path('dashboard/',dashboard,name="dashboard"),
    path('onboard/fc/',onboard_fc,name="onboard_fc"),

    path('onboard/lg/<uuid:fc_code>/',onboard_lg,name="onboard_lg"),
    path('lg/<uuid:lg_code>/',view_lg,name="view_lg"),
    path('lg/<uuid:lg_code>/add_farmer/',add_lg_farmer,name="add_lg_farmer"),
    path('lg/<uuid:lg_code>/add_product/',add_lg_product,name="add_lg_product"),
    path('lg/<str:lg_certification_code>/<uuid:product_code>/add_lg_product_to_certification/',add_lg_product_to_certification,name="add_lg_product_to_certification"),
    path('lg/<str:lg_certification_code>/',product_lg_details, name ="product_lg_details"),

    path('onboard/po/<uuid:fc_code>/',onboard_po,name="onboard_po"),
    path('po/<uuid:po_code>/add_product/',add_po_product,name="add_po_product"),    
    path('po/<uuid:po_code>/',view_po,name="view_po"),
    path('po/<str:po_certification_code>/<uuid:product_code>/add_po_product_to_certification/',add_po_product_to_certification,name="add_po_product_to_certification"),
    path('po/<str:po_certification_code>/',product_po_details, name ="product_po_details"),
    
    re_path('trace/lg/(?P<certification_id>[\w.@+-]+)/$',lgtracer),
    re_path('trace/po/(?P<certification_id>[\w.@+-]+)/$',potracer),
    
    re_path(r'^media/(?P<path>.*)$', serve, kwargs={'document_root': settings.MEDIA_ROOT}),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pgsoc/models.py
import datetime 
from django.db import models
from django.utils.translation import gettext as _
from django.db.models.signals import post_save
from django.db.models import signals
from django.core.files.base import ContentFile
from django.urls import reverse

from user.models import User 
from common.models import AbstractModel

from phonenumber_field.modelfields import PhoneNumberField
# from djmodels.TextField.models import models.TextField
from pgsoc.functions import make_qr_code


class GenericFiles(AbstractModel):
    upload = models.FileField(_("The file referrred to"), upload_to="", max_length=100)
    orig_name = models.CharField(_("Original Media name"), max_length=500,default="None")
    orig_size = models.PositiveIntegerField(_("File Size"), default=0)
    file_extension = models.CharField(_("File extension"), max_length=50,default="")

    class Meta:
        ordering=['-updated_at']

    def __str__(self):
        return str(self.orig_name)
    
    

class FacilitationCouncil(AbstractModel):
    
    membership_type_choices = (
        ("Institutional","Institutional Member"),
        ("Associate","Associate Member")
    )
    organization_choices = (
        ("society","Society"),
        ("trust","Trust"),
        ("company","Company")
    )
    
    agri_notes = models.TextField(_("Internal notes about ecology, climate etc  "),blank=True,null=True)
   
    legal_representative = models.ForeignKey("user.User", verbose_name=_("Legal Representative"), on_delete=models.CASCADE, related_name = "fc_legal_representative",blank=True,null=True)
    poc = models.ManyToManyField("user.User", verbose_name=_("Point of Contact"))
   
    is_approved = models.BooleanField(_("Is secretariat approved"),default=False)
    approved_on = models.DateTimeField(_("Approved on"), auto_now=False, auto_now_add=False,default=None,null=True,blank=True)
    approved_by = models.ForeignKey("user.User", verbose_name=_("Approved By"), on_delete=models.CASCADE, default=None, null=True, blank=True,related_name="approved_by_user" )
    
    name = models.CharField(_("FC Name"),max_length=500)
    membership_type = models.CharField(_("Membership type"),choices=membership_type_choices,default="Associate",max_length=100)
    FC_code = models.CharField(_("FC Code"),max_length=100)
    description = models.TextField(_("Description about the FC"),blank=True,null=True)
    website = models.URLField(_("Website"), max_length=200,blank=False,null= False, default="example.com")
    contact_email = models.EmailField(_("Contact Email"), max_length=254,blank=False,null=False,default="hello@example.com")
    postal_address = models.TextField(_("Postal Address"),blank=True, null=True)
    organization_type = models.CharField(_("Organization Type"), max_length=50,choices = organization_choices,default = "company")
    registration_number = models.TextField(_("Registration "),default="Not given")
    date_of_induction = models.DateField(_("Date of Induction"), auto_now=False, auto_now_add=False,blank=True, null=True)
    
    annual_audit = models.ManyToManyField("pgsoc.GenericFiles", verbose_name=_("Annual Audit Reports"),related_name="annual_audit")
    recommendation_letters = models.ManyToManyField("pgsoc.GenericFiles", verbose_name=_("Recommendation Letter"),related_name="recommendation_letter")
    registration_certificate = models.ForeignKey("pgsoc.GenericFiles", verbose_name=_("Registration Certificate"), on_delete=models.CASCADE,related_name="registration_certificate",default=None,null = True, editable = True,)
    representation_letter = models.ForeignKey("pgsoc.GenericFiles", verbose_name=_("Representation Letter"), on_delete=models.CASCADE,related_name="representation_letter",default=None,null = True, editable = True,)
    bylaws = models.ForeignKey("pgsoc.GenericFiles", verbose_name=_("ByLaws"), on_delete=models.CASCADE,related_name="bylaws",default=None,null = True, editable = True,)
    
    country = models.ForeignKey('cities_light.Country', on_delete=models.SET_NULL, null=True, blank=True) 
    city = models.ForeignKey('cities_light.City', on_delete=models.SET_NULL, null=True, blank=True)
    state = models.ForeignKey('cities_light.Region', on_delete=models.SET_NULL, null=True, blank=True)
    
    class Meta:
        verbose_name = _("Facilitation Council")
        verbose_name_plural = _("Facilitation Councils")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("FacilitationCouncil_detail", kwargs={"pk": self.pk})

class LocalGroup(AbstractModel):

    name = models.CharField(_("LG Name"),max_length=500)
    description = models.TextField(_("Description about the LG"),blank=True,null=True)
    LG_code = models.CharField(_("LG Group Code"), max_length=200)
    no_of_farmers = models.PositiveIntegerField(_("No of Farmers"))
    notes = models.TextField(_("Internal notes"),blank=True,null=True)
    village = models.CharField(_("Village"), max_length=200,null=True)
    district = models.CharField(_("District"), max_length=200,null=True)
    state = models.CharField(_("State"), max_length=100,null=True)
    convener = models.ForeignKey("pgsoc.Farmer", verbose_name=_("Convener"), on_delete=models.CASCADE,related_name="lg_convener",null=True)
    associated_farmers = models.ManyToManyField("pgsoc.Farmer", verbose_name=_("List of farmers"),related_name='lg_farmers')
    agro_ecological_zone = models.CharField(_("Agro Ecological Zones"), max_length=50,blank=True,null=True)
    agro_climatic_zone = models.CharField(_("Agro Climatic Zone"), max_length=50,blank=True,null=True)
    fc_associated = models.ForeignKey("pgsoc.FacilitationCouncil", verbose_name=_("FC Associated with"), on_delete=models.CASCADE,default=None, blank=True,null=True)
    products = models.ManyToManyField("pgsoc.Product", verbose_name=_("Products produced by LG"))
    
    class Meta:
        verbose_name = _("LocalGroup")
        verbose_name_plural = _("LocalGroups")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("LocalGroup_detail", kwargs={"pk": self.pk})

    
class ParticipatingOrganization(AbstractModel):
    
    org_type = (
        ("coop","Co-Operative"),
        ("FPO","Farmer Producer Organization"),
        ("SHG","Self Help Group"),
        ("PG","Producer Group"),
        ('RME','Repacker and Marketing entity')
    )
    
    endorsement_status_choices = (
        ("certificed","Certified"),
        ("cancelled","Cancelled"),
        ("documentation","Verification and Documentation in progress"),
        ("progress","InProgress")
    )
    
    risk_categories = (
        ("low","Low Risk"),
        ("moderate","Moderate Risk"),
        ("high","High Risk")
    )
    
    po_code = models.CharField(_("PO Code"), max_length=100,default="", blank=True,null=True)
    name = models.CharField(_("PO Name"),max_length=500)
    registration_number = models.TextField(_("Registration "),default="Not given")
    fssai_license_no = models.CharField(_("FSSAI License number"), max_length=200,blank=True,null=True)
    description = models.TextField(_("Description about the PO"),blank=True,null=True)
    org_type = models.CharField(_("Type of Organization"), max_length=50,choices=org_type)
    agri_notes = models.TextField(_("Internal notes about PO. Not visible to anybody but PGS seceratariat"),blank=True,null=True)
    is_independent = models.BooleanField(_("Independent PO"), default=False)
    fc = models.ForeignKey("pgsoc.FacilitationCouncil", verbose_name=_("FC associated to"), on_delete=models.CASCADE, blank=True, null=True)
    endorsement_status = models.CharField(_("Endorsement or Certification Status"), max_length=200,choices=endorsement_status_choices, default="progress")
    address = models.TextField(_("address of PO"),blank=False,null=False,default="Unknown")
    country = models.ForeignKey('cities_light.Country', on_delete=models.SET_NULL, null=True, blank=True) 
    city = models.ForeignKey('cities_light.City', on_delete=models.SET_NULL, null=True, blank=True)
    state = models.ForeignKey('cities_light.Region', on_delete=models.SET_NULL, null=True, blank=True)
    risk_category = models.CharField(_("Risk Category"), choices = risk_categories, max_length=50, default="high")
    is_approved = models.BooleanField(_("Is secretariat approved"),default=False)
    approved_on = models.DateTimeField(_("Approved on"), auto_now=False, auto_now_add=False,default=None,null=True,blank=True)
    approved_by = models.ForeignKey("user.User", verbose_name=_("Approved By"), on_delete=models.CASCADE, default=None, null=True, blank=True,related_name="po_approved_by_user" )
    contact_email = models.EmailField(_("Contact Email"), max_length=254,blank=False,null=False,default="hello@example.com")
    website = models.URLField(_("Website"), max_length=200,blank=False,null= False, default="example.com")
    poc = models.ManyToManyField("user.User", verbose_name=_("Point of Contact"))
    products = models.ManyToManyField("pgsoc.Product", verbose_name=_("Products produced by LG"), related_name = "po_products",blank=True,null=True)
    
    class Meta:
        verbose_name = _("Participating Organization")
        verbose_name_plural = _("Participating Organizations")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("ParticipatingOrganization_detail", kwargs={"pk": self.pk})


class ProductType(AbstractModel):

    name = models.CharField(_("Product Type"),max_length=500)
    description = models.TextField(_("Details about this product type"),blank=True,null=True)
    is_raw = models.BooleanField(_("Raw product type"),default=False)
    is_processed = models.BooleanField(_("Processed product type"),default=False)
  
    class Meta:
        verbose_name = _("ProductType")
        verbose_name_plural = _("ProductTypes")

    def __str__(self):
        return self.name

    def get_absolute_url(self):

templates/_base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{%block title%}QR Code Generator{% endblock title %}</title> 
  <meta name="description" content="PGSOC">
  <meta name="author" content="PGSOC">
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <!-- Include Choices CSS -->
  <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css"
/>
</head>
<body>

  
  <div class="container">
    <div class="sticky-top">

      <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'dashboard'%}">
            <img src="{% static 'images/pgsoc_logo.jpg'%}" alt="" width="30" height="24" class="d-inline-block align-text-top">
            PGS Organic Council
          </a>
        </div>
      </nav>
    </div>
    {% block content %}
    
    {% endblock %}
</div>


<!-- Include Choices JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js"></script>

{% block javascript %}

{% endblock javascript %}
</body>
</html>

templates/add_products.html
{% extends '_base.html' %}

{% block title %} Add Product {% endblock title %}

{% block content %}


<form class="row g-3" method="post" action=".">

    {% csrf_token %}
    <div class="col-md-12">
        <h4>Product Details </h4>
        <hr/>
        <br/>
    </div>

    <div class="col-12">
        <label for="productType" class="form-label">Product Type</label>
        <select class="form-select" required name="producttype" id="producttype" required>
            <option value="">Select type of product type</option>
        </select>
    </div>

    <div class="col-6">
        <label for="product" class="form-label">Select existing product</label>
        <select class="form-select" name="product" id="product">
            <option value="">Select type of product type</option>
        </select>
    </div>
    <div class="col-6">
        <label for="product_text" class="form-label">Add new product</label>
        <input type="text" class="form-control" id="product_text" aria-describedby="product_text_help" name="product_text">
        <div id="product_text_help" class="form-text">Use this box to add product if not already exists.</div>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>


{% endblock content %}


{% block javascript %}
<script>

const typeelement = document.getElementById("producttype")
const typechoices = new Choices(typeelement, {
    choices : [{% for p in product_types %}
                {
                label: "{{p.name}}",
                value: "{{p.uuid}}"
                },
            {% endfor %}],
    searchEnabled: true,
    searchChoices: true,
    searchFields: ['label',],
        
})
    


const element = document.getElementById("product")
const choices = new Choices(element, {
  choices : [{% for p in products %}
              {
                label: "{{p.name}}",
                value: "{{p.uuid}}"
              },
            {% endfor %}],
  searchEnabled: true,
  searchChoices: true,
  searchFields: ['label',],
        
})
</script>
{% endblock javascript%}

templates/dashboard.html
{% extends '_base.html' %}
{%block title%} Dashboard {% endblock %}

{% block content %}

<div class="row">
  <div class="col-6">
    List of PO's under {{fc.name}}   <a href="{% url 'onboard_po' fc_code=fc.uuid %}"> Onboard PO </a>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#Code </th>
            <th scope="col">PO Name</th>
            <th scope="col">Risk Category</th>
            <th scope="col">Approved</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
            {% for p in po %}
          <tr>
            <th scope="row">{{p.po_code}}</th>
            <td>{{p.name}}</td>
            <td>{{p.get_risk_category_display}}</td>
            <td>{{p.is_approved}}</td>
            <td><a href="{% url 'view_po' po_code=p.uuid%}">View </a> </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    </div>


    
    <div class="col-6">
      List of LG's under {{fc.name}}   <a href="{% url 'onboard_lg' fc_code=fc.uuid %}"> Onboard LG </a>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#Code </th>
            <th scope="col">LG Name</th>
            <th scope="col">No of Farmers</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
            {% for lg in fc_lg %}
          <tr>
            <th scope="row">{{lg.LG_code}}</th>
            <td>{{lg.name}}</td>
            <td>{{lg.no_of_farmers}}</td>
            <td><a href="{%url 'view_lg' lg_code=lg.uuid%}">View </a> </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>



{% endblock content %}

templates/lg_details.html
{% extends '_base.html' %}

{% block title%} LG Details : {{lg.name}} {% endblock title %}

{% block content %}

 Name: {{lg.name}}
 <br />
 LG Code : {{lg.LG_code}}
 <br />
 Certification Status : {% if lg_status %} {% if lg_status.is_approved is True %} {{lg_status.certification_id}} {% else %} Pending Approval {% endif %} {% else %} <form action={% url 'view_lg' lg_code=lg.uuid %} method="POST"> {% csrf_token %} <button class="btn btn-primary btn-sm " href="#" role="button"> Apply for Certification </button> </form> {% endif %}
 <br />
 Convener : {{lg.convener.name}} ({{lg.convener.contact}})
 <br/>
 Farmers:
 <br/>
    <a href="{% url 'add_lg_farmer' lg_code=lg.uuid %}"> Add farmer </a>

 <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Contact</th>
      </tr>
    </thead>
    <tbody>
        {% for farmer in lg.associated_farmers.all %}
      <tr>
        <td>{{farmer.name}}</td>
        <td>{{farmer.contact}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  Add Products:
  <br />
  <a href="{% url 'add_lg_product' lg_code=lg.uuid %}"> Add Products</a>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Contact</th>
        <th scope="col"> </th>
      </tr>
    </thead>
    <tbody>
        {% for product in lg.products.all %}
      <tr>
        <td>{{product.name}}</td>
        <td>{{product.product_type}}</td>
        <td> {% if lg_status and product in lg_status.products.all %}<a href="{%url 'product_lg_details' lg_certification_code=lg_status.certification_id%}"> View </a> {%elif lg_status %} <form action="{% url 'add_lg_product_to_certification' lg_certification_code=lg_status.certification_id product_code=product.uuid %}"> {% csrf_token %} <button class="btn btn-primary btn-sm " role="button"> Add to certification </button> {% else %} Certification not issued. Apply for certification first{% endif %}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}

templates/lgtracer.html
{% extends '_base.html' %}
{% load static %}
  

{% block content %}
  <div class="container text-center">
    <div class="row">
      <div class="col-1">
        
      </div>
      <div class="col-4">
          <img src="/{{lgc.qr_code}}" />
          {% if request.user.is_authenticated %}
            <a href="/{{lgc.qr_code}}"> Download QR Code </a>
          {% endif %}
        </div>
      <div class="col-6">
        <table class="table">
          <tbody class="gap-5">
            <tr>
              <th scope="row">Certification ID:</th>
              <td> {{lgc.certification_id}} </td>
            </tr>
            <tr>
              <th scope="row">Group code :</th>
              <td> {{lgc.lg.LG_code}} </td>
            </tr>
            <tr>
              <th scope="row">Location</th>
              <td> {{lgc.lg.village}}, {{lgc.lg.district}}, {{lgc.lg.state}}  </td>
            </tr>
            <tr>
              <th scope="row">No of Farmers</th>
              <td> {{lgc.lg.no_of_farmers}}</td>
            </tr>
            <tr>
              <th scope="row">Certificated on</th>
              <td> {{lgc.certification_start_date}}  </td>
            </tr>
            <tr>
              <th scope="row">Certificated till</th>
              <td> 
                {{lgc.certification_end_date}}*  
                <div class="alert alert-warning small"> *For product expiry date, please check the product packaging. </div>
              </td>
              
            </tr>
            <tr>
              <th scope="row">Certified crops / products</th>
              <td> 
                  {% for  product in lgc.products.all %} 
                    {% if forloop.last %}
                      {{ product.name }}
                    {% else %}
                      {{ product.name }},
                    {% endif %}
                  {% endfor %}  
              </td>
            </tr>
            {% comment %} <tr> 
              <th scope="row"> Growing environment </th>

              <td> 
                  {% if lgc.lg.agro_ecological_zone and lgc.lg.agro_climatic_zone  %}
                    {{lgc.lg.agro_ecological_zone}} and {{lgc.lg.agro_climatic_zone}} 
                  {% elif lgc.lg.agro_ecological_zone %}
                    {{lgc.lg.agro_ecological_zone}}
                  {% elif lgc.lg.agro_climatic_zone %}
                    {{lgc.lg.agro_climatic_zone}}
                  {% else %}
                    <div class="alert alert-warning small"> This information is currently unavailable. </div>
                  {% endif %}
              </td>
              </td>
            </tr> {% endcomment %}
          </tbody>
        </table>
      </div>
      <div class="col-1">
        
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/login.html
{% extends '_base.html' %}

{% block title %} Login {% endblock %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <div class="row mb-3">
      <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputEmail3" name="username">
      </div>
    </div>
    <div class="row mb-3">
      <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
      <div class="col-sm-10">
        <input type="password" class="form-control" id="inputPassword3" name="password">
      </div>
    </div>

    <button type="submit" class="btn btn-primary">Sign in</button>
  </form>

  {% endblock content %}

templates/onboard_fc_data_received.html
{% extends '_base.html' %}

{% block title%} Onboarding data received {% endblock title %}

{% block content %}

Data has been received and will be reviewed. Once approved you will receive and email with confirmation and further instructions.

{% endblock content %}

templates/onboard_lg.html
{% extends '_base.html' %}

{% block title %} Onboaring FC {% endblock title %}

{% block content %}


<form class="row g-3" method="post">

    {% csrf_token %}
    <div class="col-md-12">
        <h4>LG Details </h4>
        <hr/>
        <br/>
    </div>

    <div class="col-md-12">
      <label for="inputOrganizationName" class="form-label">LG Name</label>
      <input type="text" class="form-control" id="inputOrganizationName" required name="lg_name">
    </div>
    <div class="col-md-4">
      <label for="inputVillage" class="form-label">Village</label>
      <input type="text" class="form-control" id="inputVillage" required name="village">
    </div>
    <div class="col-md-4">
        <label for="inputDistrict" class="form-label">District</label>
        <input type="text" class="form-control" id="inputDistrict" required name="district">
    </div>
    <div class="col-md-4">
        <label for="inputState" class="form-label">State</label>
        <input type="text" class="form-control" id="inputState" required name="state">
    </div>
    <div class="col-md-12">
        <h4>Convener Details </h4>
        <hr/>
        <br/>
    </div>

    <div class="col-md-6">
        <label for="inputConvenerName" class="form-label">Convener Name</label>
        <input type="text" class="form-control" id="inputConvenerName" required name="convener_name">
      </div>
      <div class="col-md-6">
        <label for="inputConvenerContact" class="form-label">Contact</label>
        <input type="text" class="form-control" id="inputConvenerContact" required name="convener_contact">
      </div>

    <button type="submit" class="btn btn-primary"> Create LG </button>

</form>

{% endblock content %}

templates/onboard_lg_farmer.html
{% extends '_base.html' %}

{% block title %} Onboaring Farmer {% endblock title %}

{% block content %}


<form class="row g-3" method="post">

    {% csrf_token %}
    <div class="col-md-12">
        <h4>Farmer Details </h4>
        <hr/>
        <br/>
    </div>

    <div class="col-md-6">
        <label for="inputConvenerName" class="form-label">Farmer Name</label>
        <input type="text" class="form-control" id="inputConvenerName" required name="farmer_name">
      </div>
      <div class="col-md-6">
        <label for="inputConvenerContact" class="form-label">Contact</label>
        <input type="text" class="form-control" id="inputConvenerContact" required name="farmer_contact">
      </div>

    <button type="submit" class="btn btn-primary"> Add Farmer </button>

</form>

{% endblock content %}

templates/potracer.html
{% extends '_base.html' %}
{%block title%} {{poc.lg.name}} {% endblock %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-lg-1">
        
        </div>

        <div class="col-lg-5 col-sm-12 col-md-12">
            <img class="img-fluid" src="/{{poc.qr_code}}" />
            <br />
            {% if request.user.is_authenticated and poc.qr_code  %}
            <a href="/{{poc.qr_code}}"> Download QR Code </a>
            {% endif %}
        </div>
      
        <div class="col-lg-5 col-sm-12 col-md-12">
        <table class="table">
          <tbody class="gap-5">
            <tr>
              <th scope="row">Certification ID:</th>
              <td> {{poc.certification_id}} </td>
            </tr>
            <tr>
              <th scope="row">Certification Status:</th>
              <td> {% if poc.is_approved %} Certificate Valid {% else %} This Certification is invalid or not certified yet {% endif %}</td>
            </tr>
            <tr>
              <th scope="row">Organization:</th>
              <td> {{poc.po.name}} </td>
            </tr>
            <tr>
              <th scope="row">Organization type:</th>
              <td> {{poc.po.get_org_type_display}} </td>
            </tr>
            <tr>
              <th scope="row">Location</th>
              <td> {{poc.po.city}}</td>
            </tr>

            <tr>
              <th scope="row">Certificated on</th>
              <td> {{poc.certification_start_date|default_if_none:"Not apply for certification"}}  </td>
            </tr>
            <tr>
              <th scope="row">Certificated till</th>
              <td> 
                {{poc.certification_end_date}}*  
                <div class="alert alert-warning small"> *For product expiry date, please check the product packaging. </div>
              </td>
              
            </tr>
            <tr>
              <th scope="row">Certified products</th>
              <td> 
                  {% for  product in poc.products.all %} 
                    {% if forloop.last %}
                      {{ product.name }}
                    {% else %}
                      {{ product.name }},
                    {% endif %}
                  {% endfor %}  
              </td>
            </tr>
            <tr>
              <th scope="row">Facilitating Council:</th>
              <td> {{poc.po.fc.name}} </td>
            </tr>
            {% comment %} <tr> 
              <th scope="row"> Growing environment </th>

              <td> 
                  {% if poc.lg.agro_ecological_zone and poc.lg.agro_climatic_zone  %}
                    {{poc.lg.agro_ecological_zone}} and {{poc.lg.agro_climatic_zone}} 
                  {% elif poc.lg.agro_ecological_zone %}
                    {{poc.lg.agro_ecological_zone}}
                  {% elif poc.lg.agro_climatic_zone %}
                    {{poc.lg.agro_climatic_zone}}
                  {% else %}
                    <div class="alert alert-warning small"> This information is currently unavailable. </div>
                  {% endif %}
              </td>
              </td>
            </tr> {% endcomment %}
          </tbody>
        </table>
      </div>
      <div class="col-lg-1">
        
      </div>
    </div>
  </div>
  

</div>



{% endblock content %}